server:
    port: 8084

spring:
    application:
        name: AUTHENTIFICATION-SERVICE
    datasource:
        url: jdbc:postgresql://db:5432/ReferYou
        platform: POSTGRESQL
        username: backend
        password: PASSWORD

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://service-registry:8085/eureka
        instance:
            hostname: localhost
