server:
    port: 8082

spring:
    application:
        name: MODERATION-SERVICE

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://service-registry:8085/eureka
        instance:
            hostname: localhost
